# Generated by Django 5.2 on 2025-05-12 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('codigo_barras', models.CharField(max_length=25, null=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('presentacion', models.CharField(max_length=100, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['codigo_articulo'],
            },
        ),
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('canal_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_canal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'canal_cliente',
                'ordering': ['canal_id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('grupo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=5)),
                ('nombre_grupo', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'grupos_articulos',
                'ordering': ['codigo_grupo'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.articulo')),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_4', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'lista_precios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=1)),
                ('nro_identificacion', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('correo_electronico', models.EmailField(max_length=255, null=True)),
                ('nro_movil', models.CharField(max_length=15, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('canal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.canalcliente')),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombres'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.grupoarticulo'),
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('linea_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_linea', models.CharField(max_length=10)),
                ('nombre_linea', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_linea', to='core.grupoarticulo')),
            ],
            options={
                'db_table': 'lineas_articulos',
                'ordering': ['codigo_linea'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.lineaarticulo'),
        ),
        migrations.CreateModel(
            name='OrdenCompraCliente',
            fields=[
                ('pedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_pedido', models.BigIntegerField(unique=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Procesando'), (3, 'Completada'), (4, 'Cancelada')], default=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes_compra_cliente',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompraCliente',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_item', models.PositiveIntegerField(default=1)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_item_orden_compra', to='core.articulo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden_compra', to='core.ordencompracliente')),
            ],
            options={
                'db_table': 'items_ordenes_compra_cliente',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField()),
                ('fecha_pedido', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cliente')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_item', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'db_table': 'items_pedido',
                'ordering': ['pedido', 'nro_item'],
            },
        ),
    ]
